In [ ]:
import pandas as pd

df = pd.read_csv('apple_health_merged.csv')
print("Data loaded successfully. Displaying the first 5 rows:")
df.head()

Data loaded successfully. Displaying the first 5 rows:

,timestamp,basal_energy,blood_glucose,carbs,distance,heart_rate,height,insulin,physical_effort,steps,weight
0,2021-12-30 20:51:11,NaN,NaN,NaN,0.03730,NaN,NaN,NaN,NaN,52.0,NaN
1,2021-12-30 20:57:46,NaN,NaN,NaN,NaN,NaN,173.0,NaN,NaN,NaN,86.5
2,2021-12-31 06:49:14,NaN,NaN,NaN,0.02958,NaN,NaN,NaN,NaN,41.0,NaN
3,2021-12-31 07:01:45,NaN,NaN,NaN,0.01681,NaN,NaN,NaN,NaN,23.0,NaN
4,2021-12-31 07:31:17,NaN,NaN,NaN,0.11269,NaN,NaN,NaN,NaN,175.0,NaN

In [ ]:
df = df.dropna()
print("DataFrame shape after removing missing values:", df.shape)

DataFrame shape after removing missing values: (0, 11)

In [ ]:
missing_values_count = df.isnull().sum()
missing_values_percentage = 100 * df.isnull().sum() / len(df)

missing_values_df = pd.DataFrame({
    'Missing Count': missing_values_count,
    'Missing Percentage': missing_values_percentage
})

missing_values_df = missing_values_df.sort_values(by='Missing Percentage', ascending=False)

print("Missing values distribution:")
print(missing_values_df)

Missing values distribution:
                 Missing Count  Missing Percentage
timestamp                    0                 NaN
basal_energy                 0                 NaN
blood_glucose                0                 NaN
carbs                        0                 NaN
distance                     0                 NaN
heart_rate                   0                 NaN
height                       0                 NaN
insulin                      0                 NaN
physical_effort              0                 NaN
steps                        0                 NaN
weight                       0                 NaN

In [ ]:
df = pd.read_csv('apple_health_merged.csv')

missing_values_count = df.isnull().sum()
missing_values_percentage = 100 * df.isnull().sum() / len(df)

missing_values_df = pd.DataFrame({
    'Missing Count': missing_values_count,
    'Missing Percentage': missing_values_percentage
})

missing_values_df = missing_values_df.sort_values(by='Missing Percentage', ascending=False)

print("Missing values distribution (after reloading data):")
print(missing_values_df)

Missing values distribution (after reloading data):
                 Missing Count  Missing Percentage
carbs                   945789          100.000000
insulin                 945789          100.000000
height                  945785           99.999577
weight                  945783           99.999366
steps                   855128           90.414247
distance                829754           87.731407
blood_glucose           796078           84.170782
basal_energy            787844           83.300186
heart_rate              679363           71.830292
physical_effort         664203           70.227397
timestamp                    0            0.000000

In [ ]:
columns_to_drop = missing_values_df[missing_values_df['Missing Percentage'] >= 99].index.tolist()
df_cleaned = df.drop(columns=columns_to_drop)

print(f"Dropped columns: {columns_to_drop}")

# Re-calculate missing values for the cleaned DataFrame
missing_values_count_cleaned = df_cleaned.isnull().sum()
missing_values_percentage_cleaned = 100 * df_cleaned.isnull().sum() / len(df_cleaned)

missing_values_df_cleaned = pd.DataFrame({
    'Missing Count': missing_values_count_cleaned,
    'Missing Percentage': missing_values_percentage_cleaned
})

missing_values_df_cleaned = missing_values_df_cleaned.sort_values(by='Missing Percentage', ascending=False)

print("\nMissing values distribution after dropping columns with >99% missing data:")
print(missing_values_df_cleaned)

Dropped columns: ['carbs', 'insulin', 'height', 'weight']

Missing values distribution after dropping columns with >99% missing data:
                 Missing Count  Missing Percentage
steps                   855128           90.414247
distance                829754           87.731407
blood_glucose           796078           84.170782
basal_energy            787844           83.300186
heart_rate              679363           71.830292
physical_effort         664203           70.227397
timestamp                    0            0.000000

In [ ]:
numerical_cols_to_impute = [
    'steps',
    'distance',
    'blood_glucose',
    'basal_energy',
    'heart_rate',
    'physical_effort'
]

for col in numerical_cols_to_impute:
    if col in df_cleaned.columns:
        median_value = df_cleaned[col].median()
        df_cleaned[col].fillna(median_value, inplace=True)
        print(f"Imputed missing values in '{col}' with median: {median_value:.2f}")

print("\nMissing values after median imputation:")
print(df_cleaned.isnull().sum())

Imputed missing values in 'steps' with median: 65.00
Imputed missing values in 'distance' with median: 0.04
Imputed missing values in 'blood_glucose' with median: 214.00
Imputed missing values in 'basal_energy' with median: 3.59
Imputed missing values in 'heart_rate' with median: 85.00
Imputed missing values in 'physical_effort' with median: 3.70

Missing values after median imputation:
timestamp          0
basal_energy       0
blood_glucose      0
distance           0
heart_rate         0
physical_effort    0
steps              0
dtype: int64

/tmp/ipython-input-3902653203.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned[col].fillna(median_value, inplace=True)

In [ ]:
numerical_cols_to_impute = [
    'steps',
    'distance',
    'blood_glucose',
    'basal_energy',
    'heart_rate',
    'physical_effort'
]

for col in numerical_cols_to_impute:
    if col in df_cleaned.columns:
        median_value = df_cleaned[col].median()
        df_cleaned[col] = df_cleaned[col].fillna(median_value)
        print(f"Imputed missing values in '{col}' with median: {median_value:.2f}")

print("\nMissing values after median imputation:")
print(df_cleaned.isnull().sum())

Imputed missing values in 'steps' with median: 65.00
Imputed missing values in 'distance' with median: 0.04
Imputed missing values in 'blood_glucose' with median: 214.00
Imputed missing values in 'basal_energy' with median: 3.59
Imputed missing values in 'heart_rate' with median: 85.00
Imputed missing values in 'physical_effort' with median: 3.70

Missing values after median imputation:
timestamp          0
basal_energy       0
blood_glucose      0
distance           0
heart_rate         0
physical_effort    0
steps              0
dtype: int64

In [ ]:
df_cleaned['timestamp'] = pd.to_datetime(df_cleaned['timestamp'], errors='coerce')
print("Data type of 'timestamp' column after conversion:")
print(df_cleaned['timestamp'].dtype)

Data type of 'timestamp' column after conversion:
datetime64[ns]

In [ ]:
df_cleaned['year'] = df_cleaned['timestamp'].dt.year
df_cleaned['month'] = df_cleaned['timestamp'].dt.month
df_cleaned['day'] = df_cleaned['timestamp'].dt.day
df_cleaned['day_of_week'] = df_cleaned['timestamp'].dt.dayofweek
df_cleaned['hour'] = df_cleaned['timestamp'].dt.hour

print("First 5 rows of df_cleaned with new date features:")
df_cleaned.head()

First 5 rows of df_cleaned with new date features:

,timestamp,basal_energy,blood_glucose,distance,heart_rate,physical_effort,steps,year,month,day,day_of_week,hour
0,2021-12-30 20:51:11,3.589,214.0,0.037300,85.0,3.7,52.0,2021,12,30,3,20
1,2021-12-30 20:57:46,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,30,3,20
2,2021-12-31 06:49:14,3.589,214.0,0.029580,85.0,3.7,41.0,2021,12,31,4,6
3,2021-12-31 07:01:45,3.589,214.0,0.016810,85.0,3.7,23.0,2021,12,31,4,7
4,2021-12-31 07:31:17,3.589,214.0,0.112690,85.0,3.7,175.0,2021,12,31,4,7

In [ ]:
numerical_cols_for_outliers = [
    'basal_energy',
    'blood_glucose',
    'distance',
    'heart_rate',
    'physical_effort',
    'steps'
]

for col in numerical_cols_for_outliers:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_cleaned[col] = df_cleaned[col].clip(lower=lower_bound, upper=upper_bound)
    print(f"Outliers in '{col}' capped using IQR method.")

print("\nDataFrame head after outlier handling:")
df_cleaned.head()

Outliers in 'basal_energy' capped using IQR method.
Outliers in 'blood_glucose' capped using IQR method.
Outliers in 'distance' capped using IQR method.
Outliers in 'heart_rate' capped using IQR method.
Outliers in 'physical_effort' capped using IQR method.
Outliers in 'steps' capped using IQR method.

DataFrame head after outlier handling:

,timestamp,basal_energy,blood_glucose,distance,heart_rate,physical_effort,steps,year,month,day,day_of_week,hour
0,2021-12-30 20:51:11,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,30,3,20
1,2021-12-30 20:57:46,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,30,3,20
2,2021-12-31 06:49:14,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,31,4,6
3,2021-12-31 07:01:45,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,31,4,7
4,2021-12-31 07:31:17,3.589,214.0,0.037482,85.0,3.7,65.0,2021,12,31,4,7

In [ ]:
print("\nDataFrame information after cleaning and transformation:")
df_cleaned.info()

DataFrame information after cleaning and transformation:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945789 entries, 0 to 945788
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   timestamp        945789 non-null  datetime64[ns]
 1   basal_energy     945789 non-null  float64
 2   blood_glucose    945789 non-null  float64
 3   distance         945789 non-null  float64
 4   heart_rate       945789 non-null  float64
 5   physical_effort  945789 non-null  float64
 6   steps            945789 non-null  float64
 7   year             945789 non-null  int32
 8   month            945789 non-null  int32
 9   day              945789 non-null  int32
 10  day_of_week      945789 non-null  int32
 11  hour             945789 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(5)
memory usage: 68.6 MB